name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # =====================
      # BACKEND (JAVA)
      # =====================
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Backend
        run: |
          cd Backend
          mvn clean package -DskipTests

      # =====================
      # FRONTEND (NODE/REACT)
      # =====================
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Frontend dependencies
        run: |
          cd Frontend
          npm install

      - name: Build Frontend
        run: |
          cd Frontend
          npm run build